#pragma once

#include <iostream>
#include <iomanip>
#include "../bingo/bingo.hpp"

/*
 *
 * TESTS WAS GENERATED BY DEEPSEEK
 *
 */

void printTestHeader(const std::string& name) {
    std::cout << "\n========================================" << std::endl;
    std::cout << name << std::endl;
    std::cout << "========================================\n" << std::endl;
}

void printNumber(const bingo::Number& n, int indent = 0) {
    const std::string indentStr(indent * 2, ' ');

    if (!n.has_childs()) {
        std::cout << indentStr << "Constant: " << n.pattern.value << std::endl;
        return;
    }

    std::string op;
    switch (n.pattern.type) {
        case bingo::detail::OperationType::Add: op = "+"; break;
        case bingo::detail::OperationType::Multiply: op = "*"; break;
        case bingo::detail::OperationType::Power: op = "^"; break;
        default: op = "?"; break;
    }

    std::cout << indentStr << "(" << std::endl;
    printNumber(n.a(), indent + 1);
    std::cout << indentStr << "  " << op << std::endl;
    printNumber(n.b(), indent + 1);
    std::cout << indentStr << ")" << std::endl;
}

void printResult(const std::optional<std::map<int64_t, bingo::PatternBuilder>>& res) {
    if (!res) {
        std::cout << "❌ No match!" << std::endl;
        return;
    }

    std::cout << "✅ Match found! Bindings:" << std::endl;
    for (const auto& [key, value] : *res) {
        std::cout << "  var[" << key << "] = ";

        // Определяем тип значения
        if (!value.pattern.has_childs()) {
            std::cout << "constant(" << value.pattern.value << ")";
        } else {
            std::cout << "expression(";
            switch (value.pattern.type) {
                case bingo::detail::OperationType::Add: std::cout << "+"; break;
                case bingo::detail::OperationType::Multiply: std::cout << "*"; break;
                case bingo::detail::OperationType::Power: std::cout << "^"; break;
                default: std::cout << "?"; break;
            }
            std::cout << ")";
        }
        std::cout << std::endl;
    }
}

int test() {
    std::cout << "=== Bingo Pattern Matching Test ===" << std::endl << std::endl;

    // Тест 1: Базовый пример из задания
    std::cout << "Test 1: Basic pattern matching" << std::endl;
    std::cout << "-------------------------------" << std::endl;

    bingo::Number f{1222};
    std::cout << "f = 1222" << std::endl;

    f = (10_bn * f) + (10_bn * 782);
    std::cout << "After: f = (10 * 1222) + (10 * 782)" << std::endl;
    std::cout << "f structure:" << std::endl;
    printNumber(f);
    std::cout << std::endl;

    auto pattern = (10_bn * 1222) + (10_bn * 1_vr);
    std::cout << "Pattern: (10 * 1222) + (10 * var[1])" << std::endl;
    std::cout << "Pattern structure:" << std::endl;
    printNumber(pattern);
    std::cout << std::endl;

    auto res = pattern.check(f);
    std::cout << "Matching result:" << std::endl;
    printResult(res);

    if (res && res->count(1)) {
        auto& binding = (*res)[1];
        if (!binding.pattern.has_childs()) {
            std::cout << "\n✓ SUCCESS: var[1] = constant(" << binding.pattern.value << ")" << std::endl;
            std::cout << "  Expected: 782, Got: " << binding.pattern.value << std::endl;
        }
    }

    std::cout << std::endl << std::endl;

    // Тест 2: Коммутативность сложения
    std::cout << "Test 2: Commutativity of addition" << std::endl;
    std::cout << "----------------------------------" << std::endl;

    auto pattern2 = (1_vr + 5_bn);
    auto expr2a = (5_bn + 10_bn);
    auto expr2b = (10_bn + 5_bn);

    std::cout << "Pattern: var[1] + 5" << std::endl;
    std::cout << "Expr A: 5 + 10 -> ";
    auto res2a = pattern2.check(expr2a);
    printResult(res2a);

    std::cout << "Expr B: 10 + 5 -> ";
    auto res2b = pattern2.check(expr2b);
    printResult(res2b);

    std::cout << std::endl;

    // Тест 3: Коммутативность умножения
    std::cout << "Test 3: Commutativity of multiplication" << std::endl;
    std::cout << "----------------------------------------" << std::endl;

    auto pattern3 = (2_bn * 1_vr);
    auto expr3a = (2_bn * 3_bn);
    auto expr3b = (3_bn * 2_bn);

    std::cout << "Pattern: 2 * var[1]" << std::endl;
    std::cout << "Expr A: 2 * 3 -> ";
    auto res3a = pattern3.check(expr3a);
    printResult(res3a);

    std::cout << "Expr B: 3 * 2 -> ";
    auto res3b = pattern3.check(expr3b);
    printResult(res3b);

    std::cout << std::endl;

    // Тест 4: Вложенные паттерны
    std::cout << "Test 4: Nested patterns" << std::endl;
    std::cout << "-----------------------" << std::endl;

    auto pattern4 = ((1_vr + 2_bn) * 3_bn);
    auto expr4 = ((5_bn + 2_bn) * 3_bn);

    std::cout << "Pattern: (var[1] + 2) * 3" << std::endl;
    std::cout << "Expr: (5 + 2) * 3" << std::endl;
    auto res4 = pattern4.check(expr4);
    printResult(res4);

    if (res4 && res4->count(1)) {
        std::cout << "  var[1] = " << (*res4)[1].pattern.value << std::endl;
    }

    std::cout << std::endl;

    // Тест 5: Неудачное сопоставление
    std::cout << "Test 5: Failed matching" << std::endl;
    std::cout << "-----------------------" << std::endl;

    auto pattern5 = (1_vr + 2_vr);
    auto expr5 = (5_bn + 6_bn + 7_bn);

    std::cout << "Pattern: var[1] + var[2]" << std::endl;
    std::cout << "Expr: 5 + 6 + 7 (несоответствие структуры)" << std::endl;
    auto res5 = pattern5.check(expr5);
    printResult(res5);

    std::cout << std::endl;

    // Тест 6: Переменные в разных местах
    std::cout << "Test 6: Variables in multiple positions" << std::endl;
    std::cout << "----------------------------------------" << std::endl;

    auto pattern6 = (1_vr * 2_vr);
    auto expr6 = (4_bn * 5_bn);

    std::cout << "Pattern: var[1] * var[2]" << std::endl;
    std::cout << "Expr: 4 * 5" << std::endl;
    auto res6 = pattern6.check(expr6);
    printResult(res6);

    if (res6) {
        std::cout << "  Bindings: var[1]=" << (*res6)[1].pattern.value
                  << ", var[2]=" << (*res6)[2].pattern.value << std::endl;
    }

    std::cout << std::endl;

    // Тест 7: Произвольная глубина
    std::cout << "Test 7: Deep pattern matching" << std::endl;
    std::cout << "-----------------------------" << std::endl;

    auto pattern7 = ((1_vr + 2_bn) * (3_vr + 4_bn));
    auto expr7 = ((10_bn + 2_bn) * (20_bn + 4_bn));

    std::cout << "Pattern: (var[1] + 2) * (var[3] + 4)" << std::endl;
    std::cout << "Expr: (10 + 2) * (20 + 4)" << std::endl;
    auto res7 = pattern7.check(expr7);
    printResult(res7);

    if (res7) {
        std::cout << "  var[1] = " << (*res7)[1].pattern.value << std::endl;
        std::cout << "  var[3] = " << (*res7)[3].pattern.value << std::endl;
    }

    std::cout << std::endl;
    std::cout << "=== All tests completed ===" << std::endl;

    return 0;
}

#include "commutative.cpp"
