#pragma once

#include <iostream>
#include "basic.cpp"

/*
 *
 * TESTS WERE GENERATED BY DEEPSEEK
 *
 */

int test_comm() {
    std::cout << "=== Bingo Pattern Matching Extended Tests ===" << std::endl;

    // ========== 1. КОММУТАТИВНОСТЬ ==========
    printTestHeader("1. COMMUTATIVITY CORNER CASES");

    // 1.1 Множественные переменные
    std::cout << "1.1 Multiple variables in commutative ops:" << std::endl;
    auto p1 = (1_vr + 2_vr + 3_vr);
    auto e1 = (10_bn + 20_bn + 30_bn);
    std::cout << "  Pattern: var1 + var2 + var3" << std::endl;
    std::cout << "  Expr:    10 + 20 + 30" << std::endl;
    auto r1 = p1.check(e1);
    printResult(r1);
    std::cout << std::endl;

    // 1.2 Переменные и константы в разном порядке
    std::cout << "1.2 Variables and constants mixed order:" << std::endl;
    auto p2 = (5_bn + 1_vr + 3_bn);
    auto e2a = (10_bn + 5_bn + 3_bn);
    auto e2b = (3_bn + 10_bn + 5_bn);
    auto e2c = (5_bn + 3_bn + 10_bn);

    std::cout << "  Pattern: 5 + var1 + 3" << std::endl;
    std::cout << "  Expr A:  10 + 5 + 3 -> ";
    printResult(p2.check(e2a));
    std::cout << "  Expr B:  3 + 10 + 5 -> ";
    printResult(p2.check(e2b));
    std::cout << "  Expr C:  5 + 3 + 10 -> ";
    printResult(p2.check(e2c));
    std::cout << std::endl;

    // 1.3 Вложенные коммутативные операции
    std::cout << "1.3 Nested commutative operations:" << std::endl;
    auto p3 = ((1_vr * 2_bn) * (3_vr * 4_bn));
    auto e3 = ((6_bn * 2_bn) * (5_bn * 4_bn));
    std::cout << "  Pattern: (var1 * 2) * (var2 * 4)" << std::endl;
    std::cout << "  Expr:    (6 * 2) * (5 * 4)" << std::endl;
    auto r3 = p3.check(e3);
    printResult(r3);
    if (r3) {
        std::cout << "    var1 = " << (*r3)[1].pattern.value << " (expected 6)" << std::endl;
        std::cout << "    var2 = " << (*r3)[3].pattern.value << " (expected 5)" << std::endl;
    }
    std::cout << std::endl;

    // ========== 2. УГЛОВЫЕ СЛУЧАИ ПЕРЕМЕННЫХ ==========
    printTestHeader("2. VARIABLE CORNER CASES");

    // 2.1 Одна переменная матчится с несколькими позициями
    std::cout << "2.1 Same variable in multiple positions:" << std::endl;
    auto p4 = (1_vr + 1_vr);
    auto e4a = (5_bn + 5_bn);
    auto e4b = (5_bn + 3_bn);

    std::cout << "  Pattern: var1 + var1" << std::endl;
    std::cout << "  Expr A:  5 + 5 -> ";
    printResult(p4.check(e4a));
    std::cout << "  Expr B:  5 + 3 -> ";
    printResult(p4.check(e4b));
    std::cout << std::endl;

    // 2.2 Переменная матчится со сложным выражением
    std::cout << "2.2 Variable matching complex expression:" << std::endl;
    auto p5 = (1_vr + 5_bn);
    auto e5 = ((2_bn * 3_bn) + 5_bn);
    std::cout << "  Pattern: var1 + 5" << std::endl;
    std::cout << "  Expr:    (2 * 3) + 5" << std::endl;
    auto r5 = p5.check(e5);
    printResult(r5);
    if (r5 && (*r5)[1].pattern.has_childs()) {
        std::cout << "    var1 = (2 * 3)" << std::endl;
    }
    std::cout << std::endl;

    // 2.3 Переменная any (должна матчиться с чем угодно)
    std::cout << "2.3 'any' variable (value = -128):" << std::endl;
    auto p6 = (bingo::any() + 5_bn);
    auto e6a = (10_bn + 5_bn);
    auto e6b = ((2_bn * 3_bn) + 5_bn);
    std::cout << "  Pattern: any + 5" << std::endl;
    std::cout << "  Expr A:  10 + 5 -> ";
    printResult(p6.check(e6a));
    std::cout << "  Expr B:  (2*3) + 5 -> ";
    printResult(p6.check(e6b));
    std::cout << std::endl;

    // ========== 3. ГЛУБОКАЯ ВЛОЖЕННОСТЬ ==========
    printTestHeader("3. DEEP NESTING");

    // 3.1 Глубоко вложенные выражения
    std::cout << "3.1 Deeply nested expressions:" << std::endl;
    auto p7 = ((1_vr + (2_bn * 3_vr)) * 4_bn);
    auto e7 = (((5_bn + (2_bn * 6_bn)) * 4_bn));
    std::cout << "  Pattern: (var1 + (2 * var2)) * 4" << std::endl;
    std::cout << "  Expr:    ((5 + (2 * 6)) * 4)" << std::endl;
    auto r7 = p7.check(e7);
    printResult(r7);
    if (r7) {
        std::cout << "    var1 = " << (*r7)[1].pattern.value << " (expected 5)" << std::endl;
        std::cout << "    var2 = " << (*r7)[3].pattern.value << " (expected 6)" << std::endl;
    }
    std::cout << std::endl;

    // 3.2 Ассоциативность (должна нормализоваться)
    std::cout << "3.2 Associativity (should flatten):" << std::endl;
    auto p8 = (1_vr + (2_vr + 3_vr));
    auto e8 = ((5_bn + 6_bn) + 7_bn);
    std::cout << "  Pattern: var1 + (var2 + var3)" << std::endl;
    std::cout << "  Expr:    (5 + 6) + 7" << std::endl;
    auto r8 = p8.check(e8);
    printResult(r8);
    std::cout << std::endl;

    // ========== 4. НЕКОММУТАТИВНЫЕ ОПЕРАЦИИ ==========
    printTestHeader("4. NON-COMMUTATIVE OPERATIONS");

    // 4.1 Power не коммутативна
    std::cout << "4.1 Power (non-commutative):" << std::endl;
    auto p9 = (1_vr ^ 2_bn);
    auto e9a = (3_bn ^ 2_bn);
    auto e9b = (2_bn ^ 3_bn);
    std::cout << "  Pattern: var1 ^ 2" << std::endl;
    std::cout << "  Expr A:  3 ^ 2 -> ";
    printResult(p9.check(e9a));
    std::cout << "  Expr B:  2 ^ 3 -> ";
    printResult(p9.check(e9b));
    std::cout << std::endl;

    // 4.2 Смешанные коммутативные и некоммутативные
    std::cout << "4.2 Mixed commutative and non-commutative:" << std::endl;
    auto p10 = ((1_vr + 2_bn) ^ 3_vr);
    auto e10 = ((5_bn + 2_bn) ^ 4_bn);
    std::cout << "  Pattern: (var1 + 2) ^ var2" << std::endl;
    std::cout << "  Expr:    (5 + 2) ^ 4" << std::endl;
    auto r10 = p10.check(e10);
    printResult(r10);
    std::cout << std::endl;

    // ========== 5. СЛОЖНЫЕ СЦЕНАРИИ ==========
    printTestHeader("5. COMPLEX SCENARIOS");

    // 5.1 Частичное совпадение
    std::cout << "5.1 Partial match (should fail):" << std::endl;
    auto p11 = (1_vr * 2_vr * 3_vr);
    auto e11 = (4_bn * 5_bn);
    std::cout << "  Pattern: var1 * var2 * var3" << std::endl;
    std::cout << "  Expr:    4 * 5" << std::endl;
    printResult(p11.check(e11));
    std::cout << std::endl;

    // 5.2 Повторяющиеся подвыражения
    std::cout << "5.2 Repeated subexpressions:" << std::endl;
    auto p12 = ((1_vr * 2_bn) * (1_vr * 2_bn));
    auto e12 = ((3_bn * 2_bn) * (3_bn * 2_bn));
    std::cout << "  Pattern: (var1 * 2) * (var1 * 2)" << std::endl;
    std::cout << "  Expr:    (3 * 2) * (3 * 2)" << std::endl;
    auto r12 = p12.check(e12);
    printResult(r12);
    if (r12 && (*r12)[1].pattern.value == 3) {
        std::cout << "    ✓ var1 consistently bound to 3" << std::endl;
    }
    std::cout << std::endl;

    // 5.3 Конфликт связываний
    std::cout << "5.3 Binding conflict (should fail):" << std::endl;
    auto p13 = (1_vr * (1_vr + 2_bn));
    auto e13 = (3_bn * (4_bn + 2_bn));
    std::cout << "  Pattern: var1 * (var1 + 2)" << std::endl;
    std::cout << "  Expr:    3 * (4 + 2)" << std::endl;
    std::cout << "  (var1 cannot be both 3 and 4) -> ";
    printResult(p13.check(e13));
    std::cout << std::endl;

    // 5.4 Нулевые и отрицательные значения
    std::cout << "5.4 Zero and negative values:" << std::endl;
    auto p14 = (1_vr * 0_bn);
    auto e14 = (5_bn * 0_bn);
    std::cout << "  Pattern: var1 * 0" << std::endl;
    std::cout << "  Expr:    5 * 0 -> ";
    printResult(p14.check(e14));

    auto p15 = ((-5_bn) * 1_vr);
    auto e15 = ((-5_bn) * -3_bn);
    std::cout << "  Pattern: -5 * var1" << std::endl;
    std::cout << "  Expr:    -5 * -3 -> ";
    printResult(p15.check(e15));
    std::cout << std::endl;

    // 5.5 Большая арность
    std::cout << "5.5 Large arity (many operands):" << std::endl;
    auto p16 = (1_vr + 2_vr + 3_vr + 4_vr + 5_vr);
    auto e16 = (10_bn + 20_bn + 30_bn + 40_bn + 50_bn);
    std::cout << "  Pattern: var1 + var2 + var3 + var4 + var5" << std::endl;
    std::cout << "  Expr:    10 + 20 + 30 + 40 + 50" << std::endl;
    auto r16 = p16.check(e16);
    if (r16 && r16->size() == 5) {
        std::cout << "  ✓ All 5 variables matched correctly" << std::endl;
        for (int i = 1; i <= 5; ++i) {
            std::cout << "    var" << i << " = " << (*r16)[i].pattern.value << std::endl;
        }
    } else {
        std::cout << "  ❌ Failed to match all variables" << std::endl;
    }
    std::cout << std::endl;

    // ========== 6. STRESS TESTS ==========
    printTestHeader("6. STRESS TESTS");

    // 6.1 Очень глубокое дерево
    std::cout << "6.1 Very deep tree (recursion depth):" << std::endl;
    auto buildDeep = [](auto&& self, int depth) -> bingo::Number {
        if (depth == 0) return 1_bn;
        return self(self, depth - 1) + 1_bn;
    };

    auto deepPattern = bingo::any() + 1_bn;
    auto deepExpr = buildDeep(buildDeep, 50);
    std::cout << "  Pattern: any + 1" << std::endl;
    std::cout << "  Expr:    ((((1 + 1) + 1) + ... + 1) (50 levels)" << std::endl;
    auto r17 = deepPattern.check(deepExpr);
    std::cout << "  Result: " << (r17 ? "✅ Matched" : "❌ Failed") << std::endl;
    std::cout << std::endl;

    // 6.2 Много переменных
    std::cout << "6.2 Many unique variables:" << std::endl;
    auto p18 = (1_vr + 2_vr + 3_vr + 4_vr + 5_vr + 6_vr + 7_vr + 8_vr + 9_vr + 10_vr);
    auto e18 = (1_bn + 2_bn + 3_bn + 4_bn + 5_bn + 6_bn + 7_bn + 8_bn + 9_bn + 10_bn);
    std::cout << "  Pattern: var1 + var2 + ... + var10" << std::endl;
    std::cout << "  Expr:    1 + 2 + ... + 10" << std::endl;
    auto r18 = p18.check(e18);
    if (r18 && r18->size() == 10) {
        std::cout << "  ✓ All 10 variables matched uniquely" << std::endl;
    } else {
        std::cout << "  ❌ Failed" << std::endl;
    }

    std::cout << "\n========================================" << std::endl;
    std::cout << "=== ALL EXTENDED TESTS COMPLETED ===" << std::endl;
    std::cout << "========================================" << std::endl;

    return 0;
}
